FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

RUN apt-get update
RUN apt-get install -y nginx

WORKDIR /app
COPY ./Api/bin/Release/netcoreapp3.1/publish .

COPY ./scripts/startup.sh .
RUN chmod 755 /app/startup.sh

# RUN cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.BAK
COPY config/nginx.conf /etc/nginx

ENV ASPNETCORE_URLS http://+:5000

EXPOSE 5000 80

CMD ["sh", "/app/startup.sh"]
